### ISSUE TITLE
Broken link on site

### ISSUE THREAD

**Issue by thedatadavis** [rybarix/snaptail#1]
The link to the starter template points to github.com/**yourusername** instead of github.com/**rybarix**

<img width="772" alt="image" src="https://github.com/user-attachments/assets/f00550bc-e5cc-4106-9154-86e0a4e95fd6">

**Comment by rybarix** [comment]
@thedatadavis nice catch!

Thank you. I'll fixit.

**Comment by rybarix** [comment]
Fixed.
